services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: fastapi-app
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_ENV=local
    env_file:
      - .env.local
    networks:
      - be_app-network

networks:
  be_app-network:
    external: true