services:
  fastapi-app:
    image: noraknorak/ai:latest
    container_name: fastapi-app
    ports:
      - "5000:5000"
    environment:
      - FASTAPI_ENV=deploy
    env_file:
      - .env.deploy
    networks:
      - backend_app-network

networks:
  backend_app-network:
    external: true