version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile-local
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=local
    env_file:
      - .env.local

networks:
  app-network:
    external: true