version: '3.8'

services:
  flask-app:
    image: noraknorak/ai:latest
    container_name: flask_container
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env